### PR TITLE
Updated the graphql link to the new one

### PR DESCRIPTION
**Pull request by 89netraM**

### CODE REVIEW

**Review by x183 — APPROVED** [review]
Nice find! LGTM

**Review by daancs — APPROVED** [review]

**Comment by 89netraM** [comment]
The date formats has changed, but for some reason Data didn't have to update their formatting.

**Review by x183 — APPROVED** [review]
Tested it and seems to work just fine

**Comment by 89netraM** [comment]
> Tested it and seems to work just fine

Did you test the original? It didn't work for me in a Docker container without the updated formatting.

**Comment by x183** [comment]
> > Tested it and seems to work just fine
> 
> Did you test the original? It didn't work for me in a Docker container without the updated formatting.

No, just tested the latest version of this PR

**Comment by 89netraM** [comment]
> No, just tested the latest version of this PR

Okay, great! I'm not authorized to merge but any one of you can do it. I've updated the stack on Portainer to the latest build of this branch.

**Pull request merged**
